apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-operations-service
  labels:
    app: eccn-management
    context: compliance-operations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eccn-management
      context: compliance-operations
  template:
    metadata:
      labels:
        app: eccn-management
        context: compliance-operations
    spec:
      containers:
      - name: compliance-operations
        image: aciworldwide/eccn-compliance-operations:1.0.0
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: uri
        - name: PRODUCT_SERVICE_URL
          value: "http://product-portfolio-service:8080"
        - name: CLASSIFICATION_SERVICE_URL
          value: "http://classification-service:8081"
        - name: RISK_ASSESSMENT_SERVICE_URL
          value: "http://risk-assessment-service:8082"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-operations-service
  labels:
    app: eccn-management
    context: compliance-operations
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: eccn-management
    context: compliance-operations