apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-portfolio-service
  labels:
    app: eccn-management
    context: product-portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eccn-management
      context: product-portfolio
  template:
    metadata:
      labels:
        app: eccn-management
        context: product-portfolio
    spec:
      containers:
      - name: product-portfolio
        image: aciworldwide/eccn-product-portfolio:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: uri
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: product-portfolio-service
  labels:
    app: eccn-management
    context: product-portfolio
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: eccn-management
    context: product-portfolio