apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-assessment-service
  labels:
    app: eccn-management
    context: risk-assessment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eccn-management
      context: risk-assessment
  template:
    metadata:
      labels:
        app: eccn-management
        context: risk-assessment
    spec:
      containers:
      - name: risk-assessment
        image: aciworldwide/eccn-risk-assessment:1.0.0
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: uri
        - name: PRODUCT_SERVICE_URL
          value: "http://product-portfolio-service:8080"
        - name: CLASSIFICATION_SERVICE_URL
          value: "http://classification-service:8081"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: risk-assessment-service
  labels:
    app: eccn-management
    context: risk-assessment
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: eccn-management
    context: risk-assessment