services:
  mongodb:
    image: mongo:7.0
    container_name: eccn_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  eccn-management-service:
    image: eccn-management-service:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/eccn_management?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
